version: '2.3'
services:
  python:
    build: ./
    volumes:
      - ./src:/home/src
      - /tmp/.X11-unix/:/tmp/.X11-unix/
      - ./jupyter:/root/.jupyter
    runtime: nvidia
    environment:
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
    ports:
      - '6006:6006'
      - '8888:8888'
    privileged: true
    working_dir: "/home/src"
    command: jupyter notebook

    tty: true
